# Arabic translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-11-19 08:43+0100\n"
"PO-Revision-Date: 2013-08-07 22:55+0000\n"
"Last-Translator: Ibrahim Saed <ibraheem5000@gmail.com>\n"
"Language-Team: Arabic <ar@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2014-04-04 04:36+0000\n"
"X-Generator: Launchpad (build 16976)\n"
"Language: ar\n"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
#: ../apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr "هذه الحزمة لا تبدو مثبّتة بشكل صحيح"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:128
#: ../apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr "هذه ليست حزمة %s رسمية. رجاءً أزل أي حزم طرف ثالث وأعد المحاولة."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:145
#: ../apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"مثبت لديك بعض الإصدارات اللاغية من الحزم، رقِّ من فضلك الحزم التالية وتحقق "
"مما إذا ما زالت المشكلة تقع:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:269
#: ../apport/ui.py:269
msgid "unknown program"
msgstr "برنامج مجهول"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#: ../apport/ui.py:270
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "عُذرًا، أُغلق برنامج \"%s\" فجأة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:272
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1306
#: ../apport/ui.py:272 ../apport/ui.py:1306
#, python-format
msgid "Problem in %s"
msgstr "مشكلة في %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:273
#: ../apport/ui.py:273
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"لا توجد ذاكرة خالية كافية على الجهاز لتحليل المشكلة وإبلاغ المطورين آليا."

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:288
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:294
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:300
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:343
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:351
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:478
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:481
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:682
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1113
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1278
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1282
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:276
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1049
#: ../apport/ui.py:288 ../apport/ui.py:294 ../apport/ui.py:300
#: ../apport/ui.py:343 ../apport/ui.py:351 ../apport/ui.py:478
#: ../apport/ui.py:481 ../apport/ui.py:682 ../apport/ui.py:1113
#: ../apport/ui.py:1278 ../apport/ui.py:1282
msgid "Invalid problem report"
msgstr "بلاغ مشكلة غير صالح"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:289
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1284
#: ../apport/ui.py:289 ../apport/ui.py:1284
msgid "This problem report is damaged and cannot be processed."
msgstr "بلاغ المشكلة هذا  تالف ولا يمكن معالجته."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:295
#: ../apport/ui.py:295
msgid "The report belongs to a package that is not installed."
msgstr "البلاغ لحزمة غير مثبتة."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:301
#: ../apport/ui.py:301
msgid "An error occurred while attempting to process this problem report:"
msgstr "حدث خطأ أثناء محاولة معالجة تقرير الخطأ هذا:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:344
#: ../apport/ui.py:344
msgid "You are not allowed to access this problem report."
msgstr "غير مسموح لك بالنفاذ إلى بلاغ المشكلة هذا."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:347
#: ../apport/ui.py:347
msgid "Error"
msgstr "خطأ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:348
#: ../apport/ui.py:348
msgid "There is not enough disk space available to process this report."
msgstr "لا توجد مساحة قرص كافية لمعالجة هذا البلاغ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:432
#: ../apport/ui.py:432
msgid "No package specified"
msgstr "لم تُحدد حزمة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:433
#: ../apport/ui.py:433
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"تحتاج إلى تحديد حزمة أو معرف عملية (PID). أطلع على --help لمزيد من المعلومات."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:456
#: ../apport/ui.py:456
msgid "Permission denied"
msgstr "رُفض التّصريح"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:457
#: ../apport/ui.py:457
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"العملية المحددة لا تخصك. من فضلك شغل هذا البرنامج بنفس المستخدم مالك العملية "
"أو كجذر."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:459
#: ../apport/ui.py:459
msgid "Invalid PID"
msgstr "رقم عملية(PID)غير صحيح"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:460
#: ../apport/ui.py:460
msgid "The specified process ID does not belong to a program."
msgstr "رقم تعريف العملية المحدد لا ينتمي ﻷي برنامج."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:479
#: ../apport/ui.py:479
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:482
#: ../apport/ui.py:482
#, python-format
msgid "Package %s does not exist"
msgstr "الحزمة %s غير موجودة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:506
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:694
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:699
#: ../apport/ui.py:506 ../apport/ui.py:694 ../apport/ui.py:699
msgid "Cannot create report"
msgstr "تعذّر إنشاء التقرير"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:521
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:584
#: ../apport/ui.py:521 ../apport/ui.py:567 ../apport/ui.py:584
msgid "Updating problem report"
msgstr "يُحدّث تقرير المشكلة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:522
#: ../apport/ui.py:522
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"لست أنت المُبلّغ عن هذه المشكلة ولست مشترك فيها، أو أن التقرير مكرّر أو أنه "
"مغلق بالفعل.\n"
"\n"
"من فضلك أنشئ تقريرًا جديدًا باستخدام \"apport-bug\"."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:531
#: ../apport/ui.py:531
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"لست أنت المُبلّغ عن هذه المشكلة. إنّ تعليم مشكلة ما كمشكلة مُكرّرة لمشكلة "
"أخرى أسهل بكثير من نقل تعليقاتك ومرفقاتك إلى مشكلة جديدة.\n"
"\n"
"وبالتبعية، نحن ننصح بالإبلاغ عن مشكلة جديدة باستخدام \"apport-bug\" وإجراء "
"تعليق في هذه المشكلة بخصوص المشكلة الأخرى المُبلغ عنها.\n"
"\n"
"هل تود المتابعة حقًا؟"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:568
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:585
#: ../apport/ui.py:568 ../apport/ui.py:585
msgid "No additional information collected."
msgstr "لم تُجمع معلومات إضافية."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:636
#: ../apport/ui.py:636
msgid "What kind of problem do you want to report?"
msgstr "ما نوع المشكلة التي تود الإبلاغ عنها؟"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:653
#: ../apport/ui.py:653
msgid "Unknown symptom"
msgstr "عَرَض غير معروف"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:654
#: ../apport/ui.py:654
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "العَرَض\"%s\" غير معروف."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:685
#: ../apport/ui.py:685
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"بعد إغلاق هذه الرسالة رجاءً انقر على نافذة التطبيق للإبلاغ عن المشكلة "
"المتعلقة بذلك."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:695
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:700
#: ../apport/ui.py:695 ../apport/ui.py:700
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:714
#: ../apport/ui.py:714
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:716
#: ../apport/ui.py:716
msgid "Specify package name."
msgstr "حدد  اسم الحزمة."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:718
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:769
#: ../apport/ui.py:718 ../apport/ui.py:769
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:748
#: ../apport/ui.py:748
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
#: ../apport/ui.py:751
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
#: ../apport/ui.py:753
msgid "Click a window as a target for filing a problem report."
msgstr "انقر على النافذة كهدف لتقديم بلاغ عن مشكلة."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:755
#: ../apport/ui.py:755
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:757
#: ../apport/ui.py:757
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:759
#: ../apport/ui.py:759
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:761
#: ../apport/ui.py:761
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:763
#: ../apport/ui.py:763
msgid "The provided pid is a hanging application."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:765
#: ../apport/ui.py:765
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:767
#: ../apport/ui.py:767
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"في نمط الإبلاغ عن علّة، احفظ المعلومات المُجمّعة في ملف بدلًا من إرسالها. "
"هذا الملف يمكن إرساله لاحقًا من جهاز حاسوب آخر."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:771
#: ../apport/ui.py:771
msgid "Print the Apport version number."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:911
#: ../apport/ui.py:911
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr "هذا سينفّذ أمر apport-retrace في نافذة طرفية لتحليل الانهيار."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:912
#: ../apport/ui.py:912
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:913
#: ../apport/ui.py:913
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:915
#: ../apport/ui.py:915
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:991
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1001
#: ../apport/ui.py:991 ../apport/ui.py:1001
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "هذا البلاغ ينطبق على برنامج لم يعد مثبتًا على حاسوبك."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1016
#: ../apport/ui.py:1016
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "حدثت المشكلة مع برنامج '%s' الذي تغير منذ حدوث الانهيار."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1114
#: ../apport/ui.py:1114
msgid "Could not determine the package or source package name."
msgstr "تعذّر تحديد اسم الحزمة أو اسم الحزمة المصدر."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1132
#: ../apport/ui.py:1132
msgid "Unable to start web browser"
msgstr "تعذّر تشغيل المتصفح"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1133
#: ../apport/ui.py:1133
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "تعذّر تشغيل المتصفح لفتح %s."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1232
#: ../apport/ui.py:1232
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "برجاء إدخال معلومات حسابك لنظام تتبع العلل لـ %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1244
#: ../apport/ui.py:1244
msgid "Network problem"
msgstr "مشكلة في الشبكة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1246
#: ../apport/ui.py:1246
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"لا يمكن الاتصال بقاعدة بيانات الانهيارات. من فضلك تحقق من اتصالك بالإنترنت."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1273
#: ../apport/ui.py:1273
msgid "Memory exhaustion"
msgstr "نفذت الذاكرة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1274
#: ../apport/ui.py:1274
msgid "Your system does not have enough memory to process this crash report."
msgstr "لا توجد ذاكرة كافية في النظام لمعالجة بلاغ الانهيار هذا."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1309
#: ../apport/ui.py:1309
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"لا يمكن الإبلاغ عن المشكلة:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1365
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1372
#: ../apport/ui.py:1365 ../apport/ui.py:1372
msgid "Problem already known"
msgstr "المشكلة معروفة"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1366
#: ../apport/ui.py:1366
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"بُلّغ عن هذه المشكلة مسبقًا في بلاغ العِلة المعروض في المتصفح، تحقق من فضلك "
"مما إذا كان باستطاعتك إضافة معلومات أخرى قد تساعد المطورين."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1373
#: ../apport/ui.py:1373
msgid "This problem was already reported to developers. Thank you!"
msgstr "بُلّغ عن هذه المشكلة مُسبقًا. شكرًا لك!"

#: ../debian/tmp/usr/bin/apport-cli.py:74 ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "اضغط على أي مفتاح للمواصلة..."

#: ../debian/tmp/usr/bin/apport-cli.py:81 ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "مالذي تود أن تفعل؟ خياراتك هي:"

#: ../debian/tmp/usr/bin/apport-cli.py:85 ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "اختر من فضلك (%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:148 ../bin/apport-cli.py:148
#, python-format
msgid "(%i bytes)"
msgstr "(%i بايتات)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:142 ../kde/apport-kde.py:342
#: ../debian/tmp/usr/share/apport/apport-kde.py:342
#: ../debian/tmp/usr/bin/apport-cli.py:150 ../gtk/apport-gtk.py:142
#: ../bin/apport-cli.py:150
msgid "(binary data)"
msgstr "(بيانات ثنائية)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:177 ../kde/apport-kde.py:162
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:286
#: ../debian/tmp/usr/share/apport/apport-kde.py:162
#: ../debian/tmp/usr/bin/apport-cli.py:178 ../gtk/apport-gtk.py:177
#: ../bin/apport-cli.py:178
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:404
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:429
msgid "Send problem report to the developers?"
msgstr "أأبلغ المطورين عن المشكلة؟"

#: ../debian/tmp/usr/bin/apport-cli.py:179 ../bin/apport-cli.py:179
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"بعد الإبلاغ عن المشكلة، من فضلك املأ النموذج المفتوح تلقائيا\n"
"في متصفح شبكة الوب."

#: ../debian/tmp/usr/bin/apport-cli.py:182 ../bin/apport-cli.py:182
#, python-format
msgid "&Send report (%s)"
msgstr "أر&سل البلاغ (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:186 ../bin/apport-cli.py:186
msgid "&Examine locally"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:190 ../bin/apport-cli.py:190
msgid "&View report"
msgstr "اعرض ال&بلاغ"

#: ../debian/tmp/usr/bin/apport-cli.py:191 ../bin/apport-cli.py:191
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "ا&حتفظ بملف البلاغ لإرساله لاحقاً أو نسخه إلى مكان آخر"

#: ../debian/tmp/usr/bin/apport-cli.py:192 ../bin/apport-cli.py:192
msgid "Cancel and &ignore future crashes of this program version"
msgstr "ألغ و &تجاهل الانهيارات المستقبلية لإصدارة البرنامج هذه"

#: ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/bin/apport-cli.py:271
#: ../debian/tmp/usr/bin/apport-cli.py:303
#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:194
#: ../bin/apport-cli.py:271 ../bin/apport-cli.py:303 ../bin/apport-cli.py:324
msgid "&Cancel"
msgstr "أل&غِ"

#: ../debian/tmp/usr/bin/apport-cli.py:222 ../bin/apport-cli.py:222
msgid "Problem report file:"
msgstr "ملف بلاغ المشكلة:"

#: ../debian/tmp/usr/bin/apport-cli.py:228
#: ../debian/tmp/usr/bin/apport-cli.py:233 ../bin/apport-cli.py:228
#: ../bin/apport-cli.py:233
msgid "&Confirm"
msgstr "&أكد"

#: ../debian/tmp/usr/bin/apport-cli.py:232 ../bin/apport-cli.py:232
#, python-format
msgid "Error: %s"
msgstr "خطأ: %s"

#: ../kde/apport-kde.py:387 ../debian/tmp/usr/share/apport/apport-kde.py:387
#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Collecting problem information"
msgstr "يجمع معلومات عن المشكلة"

#: ../debian/tmp/usr/bin/apport-cli.py:239 ../bin/apport-cli.py:239
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"يمكن إرسال المعلومات التي جُمِعت إلى المطورين لتحسين\n"
"التطبيق، لكن قد يستغرق هذا بعض الدقائق."

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
#: ../kde/apport-kde.py:415 ../debian/tmp/usr/share/apport/apport-kde.py:415
#: ../debian/tmp/usr/bin/apport-cli.py:251 ../bin/apport-cli.py:251
msgid "Uploading problem information"
msgstr "يرفع معلومات المشكلة"

#: ../debian/tmp/usr/bin/apport-cli.py:252 ../bin/apport-cli.py:252
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"يجري إرسال المعلومات التي جُمِعت إلى نظام تتبع العِلَل،\n"
"لكن قد يستغرق هذا بضع دقائق."

#: ../debian/tmp/usr/bin/apport-cli.py:302 ../bin/apport-cli.py:302
msgid "&Done"
msgstr "&تمّ"

#: ../debian/tmp/usr/bin/apport-cli.py:308 ../bin/apport-cli.py:308
msgid "none"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:309 ../bin/apport-cli.py:309
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
msgid "Choices:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:339 ../bin/apport-cli.py:339
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:345 ../bin/apport-cli.py:345
msgid "File does not exist."
msgstr "الملف غير موجود."

#: ../debian/tmp/usr/bin/apport-cli.py:347 ../bin/apport-cli.py:347
msgid "This is a directory."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:353 ../bin/apport-cli.py:353
msgid "To continue, you must visit the following URL:"
msgstr "للمواصلة، يجب عليك زيارة الرابط التالي:"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"يمكنك تشغيل المتصفح الآن، أو انسخ هذا العنوان إلى متصفح على حاسوب آخر."

#: ../debian/tmp/usr/bin/apport-cli.py:357 ../bin/apport-cli.py:357
msgid "Launch a browser now"
msgstr "شغّل المتصفح الآن"

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid "No pending crash reports. Try --help for more information."
msgstr "لا يوجد تقارير بلاغات معلقة. جرب --help لمزيد من المعلومات."

#: ../data/apportcheckresume.py:68
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""

#: ../data/apportcheckresume.py:70
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""

#: ../data/apportcheckresume.py:75
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:31 ../bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:33 ../bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:35 ../bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:37 ../bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "اكتب تقرير مُعدّل للملف المُعطى بدلًا من تغيير التقرير الأصلي"

#: ../debian/tmp/usr/bin/apport-retrace.py:39 ../bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-retrace.py:59
#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:70 ../bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:76 ../bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:80 ../bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:114 ../bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr "أبلغ عن مشكلة..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "أبلغ المطورين عن خلل"

#: ../data/kernel_oops.py:30 ../debian/tmp/usr/share/apport/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr "قد يصبح نظامك غير مستقر الآن وقد يحتاج لإعادة تشغيله."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:157 ../gtk/apport-gtk.py:157
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "عُذرًا، توقف التطبيق \"%s\" فجأة"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:160 ../gtk/apport-gtk.py:160
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "عُذرًا، أُغلق \"%s\" فجأة."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:165 ../kde/apport-kde.py:176
#: ../kde/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:110
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:254
#: ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:217 ../gtk/apport-gtk.py:165
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:300
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "عُذرًا، واجه \"%s\" خطأ داخليا."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:186 ../kde/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:292
#: ../debian/tmp/usr/share/apport/apport-kde.py:170 ../gtk/apport-gtk.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:412
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:437
msgid "Send"
msgstr "أرسل"

#: ../gtk/apport-gtk.ui.h:7 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:573 ../kde/apport-kde.py:271
#: ../debian/tmp/usr/share/apport/apport-kde.py:271 ../gtk/apport-gtk.py:204
#: ../gtk/apport-gtk.py:573
msgid "Show Details"
msgstr "أظهر التفاصيل"

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/apport-gtk.py:303 ../kde/apport-kde.py:210
#: ../kde/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:141
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:153
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:262
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:332
#: ../debian/tmp/usr/share/apport/apport-kde.py:210
#: ../debian/tmp/usr/share/apport/apport-kde.py:223 ../gtk/apport-gtk.py:216
#: ../gtk/apport-gtk.py:284 ../gtk/apport-gtk.py:303
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:350
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:479
msgid "Continue"
msgstr "واصِل"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:228 ../gtk/apport-gtk.py:228
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:276
msgid "Force Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:229
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288 ../kde/apport-kde.py:214
#: ../kde/apport-kde.py:361
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:226
#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-kde.py:361 ../gtk/apport-gtk.py:229
#: ../gtk/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:232
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:273
msgid "Relaunch"
msgstr "شغّله مجددا"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:238 ../gtk/apport-gtk.py:238
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:242 ../gtk/apport-gtk.py:242
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:257 ../kde/apport-kde.py:184
#: ../debian/tmp/usr/share/apport/apport-kde.py:184 ../gtk/apport-gtk.py:257
#, python-format
msgid "Package: %s"
msgstr "الحزمة: %s"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:264 ../kde/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:136
#: ../debian/tmp/usr/share/apport/apport-kde.py:190 ../gtk/apport-gtk.py:264
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
msgid "Sorry, a problem occurred while installing software."
msgstr "عُذرًا، حدث خطأ أثناء تثبيت البرنامج."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:273
#: ../debian/tmp/usr/share/apport/apport-gtk.py:292 ../kde/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/apport-kde.py:197 ../gtk/apport-gtk.py:273
#: ../gtk/apport-gtk.py:292
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "واجه تطبيق \"%s\" خطأ داخليا."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:276 ../kde/apport-kde.py:201
#: ../debian/tmp/usr/share/apport/apport-kde.py:201 ../gtk/apport-gtk.py:276
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "أُغلق تطبيق \"%s\" فجأة."

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:287 ../kde/apport-kde.py:213
#: ../debian/tmp/usr/share/apport/apport-kde.py:213 ../gtk/apport-gtk.py:287
msgid "Leave Closed"
msgstr "اتركه مغلقا"

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/apport-gtk.py:300 ../kde/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:256
#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../gtk/apport-gtk.py:300
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:302
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:342
msgid "If you notice further problems, try restarting the computer."
msgstr "إذا لاحظت المزيد من المشاكل، جرّب إعادة تشغيل الحاسوب."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:304 ../kde/apport-kde.py:224
#: ../debian/tmp/usr/share/apport/apport-kde.py:224 ../gtk/apport-gtk.py:304
msgid "Ignore future problems of this type"
msgstr "تجاهل الانهيارات المستقبلية لهذا النوع"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:577 ../kde/apport-kde.py:268
#: ../debian/tmp/usr/share/apport/apport-kde.py:268 ../gtk/apport-gtk.py:577
msgid "Hide Details"
msgstr "أخفِ التفاصيل"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../kde/apport-kde.py:294 ../debian/tmp/usr/share/apport/apport-kde.py:294
msgid "Username:"
msgstr "اسم المستخدم:"

#: ../kde/apport-kde.py:295 ../debian/tmp/usr/share/apport/apport-kde.py:295
msgid "Password:"
msgstr "كلمة السر:"

#: ../kde/apport-kde.py:386 ../debian/tmp/usr/share/apport/apport-kde.py:386
msgid "Collecting Problem Information"
msgstr ""

#: ../kde/apport-kde.py:388 ../debian/tmp/usr/share/apport/apport-kde.py:388
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"يمكن إرسال المعلومات التي جُمِعت إلى المطورين لتحسين التطبيق، قد يستغرق هذا "
"بضع دقائق."

#: ../kde/apport-kde.py:414 ../debian/tmp/usr/share/apport/apport-kde.py:414
msgid "Uploading Problem Information"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
#: ../kde/apport-kde.py:416 ../debian/tmp/usr/share/apport/apport-kde.py:416
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"يجرى إرسال المعلومات التي جُمِعت إلى نظام تتبع العِلَل، وقد يستغرق هذا بضع "
"دقائق."

#: ../gtk/apport-gtk.ui.h:1 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:450 ../kde/apport-kde.py:486
#: ../debian/tmp/usr/share/apport/apport-kde.py:450
#: ../debian/tmp/usr/share/apport/apport-kde.py:486
msgid "Apport"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr "الاستيثاق مطلوب لجمع معلومات النظام لتقرير العلة هذا"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr "برجاء إدخال كلمة سرك للنفاذ إلى تقارير المشاكل لبرامج النظام"

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "بلاغ انهيار"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>عُذرًا، حدث خطأ داخلي.</b></big>"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr "إرسال تقرير عن الخطأ للمساعدة في إصلاح هذه المشكلة"

#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "تجاهل الانهيارات المستقبلية لإصدارة البرنامج هذه"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>يجمع معلومات عن المشكلة</b></big>"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"يجري جمع المعلومات التي قد تساعد المطورين في إصلاح المشكلة المبلغ عنها."

#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>يرفع معلومات المشكلة</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "يمكنك مساعدة المطورين في إصلاح المشكلة بالإبلاغ عنها."

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">عفواً، فشِل تثبيت أو ترقية حزمة "
#~ "\"%s\".</span>"

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "بلاغ كامل (موصى به; %s)"

#~ msgid "Content of the report"
#~ msgstr "محتوى البلاغ"

#~ msgid "Restart _Program"
#~ msgstr "أعد تشغيل ال_برنامج"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr "بإمكانك مساعدة المطورين في إصلاح الحزمة بالإبلاغ عن المشكلة."

#~ msgid "&Report Problem..."
#~ msgstr "&أبلغ عن مشكلة..."

#~ msgid "_Report Problem..."
#~ msgstr "_أبلغ عن مشكلة"

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "أُغلق %s فجأة في %s عند %s."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "فشِل تثبيت أو ترقية حزمة \"%s\"."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "هذه ليست حزمة %s أصلية"

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "واجه النظام مشكلة خطيرة بالنواة."

#~ msgid "Application problem"
#~ msgstr "مشكلة في التطبيق"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>هل أبلغ المطورين عن المشكلة؟</b></big>\n"
#~ "\n"
#~ "من فضلك بعد الإبلاغ عن المشكلة املأ النموذج في متصفح الوب المفتوح تلقائيا."

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "بلاغ مختصر (اتصال إنترنت بطيء; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "سيُزِيل هذا أجزاء كبيرة من البلاغ، وهي مفيدة للغاية للمطورين في تنقيح "
#~ "المشكلة لكنها قد تكون كبيرة جداً عند الرفع إذا كان اتصالك بالإنترنت بطيء."

#~ msgid "Package problem"
#~ msgstr "مشكلة في حزمة"

#~ msgid "Kernel problem"
#~ msgstr "مشكلة في النواة"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "يمكنك إذا لم يكن ما تفعله سرّي (تدخل كلمات سرية أو معلومات خاصة) فيمكنك "
#~ "المساعدة في تحسين التطبيق بالإبلاغ عن المشكلة."

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_تجاهل الانهيارات المستقبلية من إصدارة البرنامج هذه"

#~ msgid "_Send Report"
#~ msgstr "_أرسل البلاغ"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "إذا لم يكن ما تفعله سرّي (تدخل كلمات سرية أو\n"
#~ "معلومات خاصة أخرى) فيمكنك المساعدة في تحسين التطبيق بالإبلاغ عن\n"
#~ "المشكلة."

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "أرسل بلاغا مختصرا (اتصال إنترنت بطيء؛ %s)"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&أرسل بلاغا كاملا (يوصى به؛ %s)"

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "عُذرًا، أُغلق تطبيق \"%s\" فجأة."
